### ISSUE TITLE
Support .Net Standard 2.0 runtime, and with that integrate it in Unity for basic string evaluation from remote.

### ISSUE THREAD

**Issue by PratapDafedar** [codingseb/ExpressionEvaluator#133]
Hi,
First of all great library! Thank you for keeping it open for the community.

I would like to know, whether it is practically possible to port it for .net standard 2.0 or are there any limitations to not doing so with the current dependencies.

If yes, then with the right suggestion and direction from you, I would like to port it for .net standard 2.0 runtime and use it in my various Unity mobile projects. 

If not, kindly suggest if there are any alternatives to achieve it. Thank you.

**Comment by PratapDafedar** [comment]
Hi @codingseb, 

I am getting following errors when I integrate it in Unity which has .net standard 2.0 runtime:

```
Assets/RuntimeStringEvaluator/ExpressionEvaluator/ExpressionEvaluator.cs(1744,9): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
Assets/RuntimeStringEvaluator/ExpressionEvaluator/ExpressionEvaluator.cs(4171,23): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.Convert'
```

But the same script works fine without any issues in **.Net 4.x**. So looks like "**dynamic** type is not supported.

**Comment by codingseb** [comment]
OK. I don't know Unity and I never worked with it.

But apparently in other projects some people that had theses errors needed to add manually these nugets or references:
* `Microsoft.CSharp` (EE 1.4.37 use version 4.7.0)
* `System.Dynamic.Runtime` (EE 1.4.37 use version 4.3.0)

If you use ExpressionEvaluator by copying the .cs file it look logical that it could be the solution.
It works in .net4.x because these references are included in the runtime.
With .netstandard dependencies are nugets so dependencies come with when EE is installed by nuget but not when just copying the ÈxpressionEvaluator.cs` so we need to install it manually.

Here some link that could explain it 
[Link1](https://social.msdn.microsoft.com/Forums/vstudio/en-US/2b855369-a721-4010-9e33-72d699960994/how-to-fix-missing-compiler-member-error-microsoftcsharpruntimebindercsharpargumentinfocreate?forum=visualstudiogeneral)
[Link2](https://mikaelkoskinen.net/post/net-core-standard-missing-compiler-required-member)
[Link3](https://stackoverflow.com/questions/40930080/asp-net-core-1-1-compiling-with-c-sharp-dynamic-missing-compiler-required-member)

**Comment by PratapDafedar** [comment]
```
Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS1703: Multiple assemblies with equivalent identity have been imported: '/Users/abcd/workspace/StringScript/Assets/RuntimeStringEvaluator/ExpressionEvaluator/System.Dynamic.Runtime.dll' and '/Applications/Unity/Hub/Editor/2019.4.32f1/Unity.app/Contents/NetStandard/compat/2.0.0/shims/netstandard/System.Dynamic.Runtime.dll'. Remove one of the duplicate references.
```

It looks like Unity internally supplies similar kind of dll in .net standard 2.0 for both the above mentioned dlls, but with the lesser API support. So, in theory it is advised to use the build-in ones and looks like they lack the support for `dynamic` and other runtime features.

So far only way I found is to target .Net 4.x in Unity if anyone wants to use your library straight out of the box. 

Otherwise this library may need major modification to avoid using above dlls as dependency and implement in alternative way.

**Comment by codingseb** [comment]
Yes apparently Unity do not support `dynamic` keyword when it use its' IL2CPP in place of JIT compilation [according to Unity doc](https://docs.unity3d.com/2022.2/Documentation/Manual/ScriptingRestrictions.html).
As I do not work with Unity, I don't know if others workaround are possible on their side to allow `dynamic`.

As ExpressionEvaluator rely on `dynamic`for a lot of functionalities. I think it's complicate to modify it to not use `dynamic`and keep the same level of functionality.

Maybe I should add a warning in the readme or the doc that it's not compatible with some mode of compilation of Unity.

**Comment by PratapDafedar** [comment]
Thank you @codingseb for your input. I will see what I can do from here.
