### ISSUE TITLE
Using namespace syntax

### ISSUE THREAD

**Issue by guylando** [codingseb/ExpressionEvaluator#19]
For example to use WebUtility.UrlEncode method from inside System.Net namespace without adding the namespace to the namespace list I would like to execute something like:
"System.Net.WebUtility.UrlEncode(...)"
Is it possible somehow? because it returns an error that "System" variable is not recognized. This would allow to execute a lot of methods without needing to add the namespace each time.

**Comment by codingseb** [comment]
Yes. You are right it could be practical.
I will look what I can do to allow inline namespaces.

**Comment by codingseb** [comment]
I just published a new version (1.3.2.0) that allow inline namespaces.

Just take note that the evaluation of inline namespaces is slower than adding namespaces in the list.
This because of the way of C# give access to namespaces with reflection (only through the types). 
So ExpressionEvaluator test at each level of the namespace if it can find a type in each assembly loaded until it find the type (class).
So depending on how you use it you will not see the difference but if you use it in loops or for filtering things it can lead to bad perfs.

I also created a option to disable it.
```c#
evaluator.OptionInlineNamespacesEvaluationActive = false;
```
See the corresponding [doc on the new wiki](https://github.com/codingseb/ExpressionEvaluator/wiki/C%23-Types-Management#inline-namespaces)
