### ISSUE TITLE
Cast error when OptionForceIntegerNumbersEvaluationsAsDoubleByDefault is true

### ISSUE THREAD

**Issue by mcicognani** [codingseb/ExpressionEvaluator#33]
Hi everybody,
I noticed that when OptionForceIntegerNumbersEvaluationsAsDoubleByDefault is turned on, the Round function would throw an Invalid cast exception.

The problem in around line 471, where:
`return Math.Round(Convert.ToDouble(self.Evaluate(args[0])), (int)self.Evaluate(args[1]), (MidpointRounding)self.Evaluate(args[2]));`

tries to cast to int a (now forced) Double value.

I suggest to substitute the cast with a Convert.ToInt32()

Same thing a few rows down, always with Math.Round() call.

**Comment by codingseb** [comment]
Hi @mcicognani.
Thanks for this issue.  

I made the correction in the dev branch with an other correction of the same kind when declaring an array with `new string[2]` for example.

It will be available in Version 1.3.7.0

*Otherwise double values can be cast back directly in expression like this `(int)5` it use the `Convert` class internally so the cast should works.*

**Comment by codingseb** [comment]
Just published v : 1.3.7.0
