### ISSUE TITLE
Evaluating null produce reference error

### ISSUE THREAD

**Issue by TheoVC** [codingseb/ExpressionEvaluator#51]
Evaluating a simple expression like

null?.Trim()

should return null

but instead is returning an exception "reference not set to an instance of an object"

**Comment by TheoVC** [comment]
![image](https://user-images.githubusercontent.com/16392893/83696560-5a925780-a5c2-11ea-8f24-234b6fd9571a.png)

the problem is in the EvaluateVarOrFunc() line 1781 the obj is null

**Comment by TheoVC** [comment]
changed the line adding the ?:
`Type[] inferedGenericsTypes = obj?.GetType().GenericTypeArguments;`

and aparently fix the issue... but I'm not an expert

**Comment by codingseb** [comment]
Hello @TheoVC  Thanks to opening this issue. I will look at this bug as soon as possible and pubish a corrective version.

**Comment by codingseb** [comment]
Your correction is right for this bug. 
But I realised that there is a other bug with null conditional operator.
When you evaluate something like : 
`null?.Trim().Length`
It generate a NullReferenceException when evaluating `Length` In C# it does not because.
Null conditional when null should not evaluate other Sub properties, methods and indexing.
I will also correct this bug before publishing the corrective version.

**Comment by codingseb** [comment]
OK I just published Version 1.4.10.0 of ExpressionEvaluator that contains corrections for these bugs.
Thanks again to reporting this.
