### ISSUE TITLE
Invalid Evaluation

### ISSUE THREAD

**Issue by BChip** [codingseb/ExpressionEvaluator#55]
Pow(2,((2+2/3)*2)) + (123-7) = 156.31747359...

Expression Evaluator evaluates Pow(2,((2+2/3)*2)) + (123-7) = 132

**Comment by codingseb** [comment]
Hello @BChip.

This is right, it's because `2/3` is evaluated as int like in C#. You can force the 3 to be evaluated as a double like this:
`Pow(2,((2+2/3d)*2)) + (123-7)` 
or 
`Math.Pow(2,((2+2/(double)3)*2)) + (123-7)`.

Otherwise you can set the following option :
```c#
evaluator.OptionForceIntegerNumbersEvaluationsAsDoubleByDefault = true;
```
[See the doc here](https://github.com/codingseb/ExpressionEvaluator/wiki/Options#optionforceintegernumbersevaluationsasdoublebydefault)

[See live examples here](https://dotnetfiddle.net/7MFZqo)

The goal of ExpressionEvaluator is to be as near as C# as possible by default. 
But you can easily customize it with options, extensions and inheritance.

**Comment by BChip** [comment]
Awesome!!! Thanks for the clarification!
