### ISSUE TITLE
Sum of decimal fail

### ISSUE THREAD

**Issue by TheoVC** [codingseb/ExpressionEvaluator#65]
the library is resolving sum like an integer... not diferenciating if a property is a decimal... probably it's failing for another datatypes like float, double, etc.

```
var Persons = new List<Person>() { new Person() { Code = "QT00010", Name = "Pedrito", Number = 11.11m },
            new Person() { Code = "QT00011", Name = "Pablito", Number = 12.11m }};

ExpressionEvaluator evaluator = new ExpressionEvaluator();
evaluator.Context = new { Persons };
object val1 = evaluator.Evaluate("Persons.Sum(x=>x.Number)");
Console.WriteLine(val1);

public class Person{
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Number { get; set; }
}
```
this should print a decimal 23.22, but it's printing an int 23

**Comment by codingseb** [comment]
Hye @TheoVC, thank you for this issue.
In fact I already came across this bug. And for now, I do not know how to correct it.

The problem come from the fact everything is evaluate "on the fly". So when the method `Sum` is evaluate there is no way I can figure out what type is the given lambda of. The lambda that is a pseudo lambda by the way because internally it's a generic delegate that make a `evaluator.Evaluate(...)`. In this case by default it take the first method that could correspond to `Sum` in `List`.

So I will keep this issue open and try to figure it out how to manage this better. But for now I am stuck on this one. So It could take time before a solution is found. Maybe with a version 2.0 of ExpressionEvaluator (see #58) that could implement a syntaxic tree it will be easier to manage. Otherwise if you have any good idea or someone else. You are welcome.

**Comment by TheoVC** [comment]
Hi @codingseb 

Hope it will help.

Pseudocode:
Find a method whose name equals to "Sum" (or whatever) with one parameter (or two if it's an extension method)
if( found only one ){
  directly call that method
}
else{
  Found some overloaded methods, so we have to 
  peek the type evaluating the lamba expression for the first element on the list (or maybe evaluating the first N elements until the result != null)
  select the corresponding method with the resulting type.
}

I know it's not fancy or elegant... but it will work

**Comment by codingseb** [comment]
Hi @TheoVC.

Thanks for your suggestion.
Yes it's not so elegant but as I do not have any other solution for now.
I will look if I can implement something like that.

**Comment by codingseb** [comment]
OK It was not so obvious but I figured it out how to implement something like what you suggested.
For now it manage some Linq methods that are define in Enumerable (Sum, Average, Min, Max)
I already publish version 1.4.15.0 that contains this hack. 
I hope to find a more generic solution for this. But at least for now it allow a better use of standard linq methods.

**Comment by codingseb** [comment]
I keep this open. As a reminder to find a better solution.

**Comment by codingseb** [comment]
OK last versions with better method selection and type inference manage this the correct way I think so I close this issue
