### ISSUE TITLE
[question] funding

### ISSUE THREAD

**Issue by lofcz** [codingseb/ExpressionEvaluator#74]
There seems to be no way to support this project financially, do you think it would be possible to either mark this project as open for github sponsors or add PayPal / whatever payment gate link? I (and possibly others) would like to chip in to support this.

**Comment by codingseb** [comment]
Wow !!!
Thank you sincerely for your interest in this project.

At the beginning it was only a small project in my spare time and it is always a spare time project.
As I use for my job and myself a lot of free and open source projects, sharing it was only an idea that maybe it could be useful for others and a way for me to give back to the community with a small contribution to opensource.

Yes, since about 3 or 4 years now I put quite a lot of work and reflection in it. I also see more and more people showing their interest by the number of stars on github and the number of download of the nuget package that keep rising.
But also by opened issues and pull request that are bugs but also suggestions and good ideas that make ExpressionEvaluator better. 

Of course some financially support would be greatly appreciate if you like this project. 
But be free to use it for free. I am really ok with this. 
I will look how to add sponsoring or donate button for people that want to say thanks this way.

Also take note that ExpressionEvaluator is free and MIT licenced and it will always be so.
As I work full time in a job that I love and that I also have a few other projects nearby and a family.
As long as people are interested in it, I will do my best to continue to put some work in ExpressionEvaluator. 
But I can not ensure that I will always put the same amount of time and energy on it.

Of course this project is still very interesting for me and I love working on it.

**Comment by lofcz** [comment]
I couldn't find any way to contact you privately but if possible leave me an invoice for 50$ via PayPal / Payoneer / some other gate you use. Thanks for this lib!

**Comment by codingseb** [comment]
I added a section donate to the homepage of this repo. [Here](https://github.com/codingseb/ExpressionEvaluator/blob/master/README.md#donate).

Thank you very much.

**Comment by lofcz** [comment]
> I added a section donate to the homepage of this repo. [Here](https://github.com/codingseb/ExpressionEvaluator/blob/master/README.md#donate).
> 
> Thank you very much.

Thanks for adding this!

![image](https://user-images.githubusercontent.com/10260230/103864960-be827e80-50c3-11eb-821d-866595863814.png)
